apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translator-web-ingress
  labels:
    app: translator-web
spec:
  rules:
    - host: translator-web.page-translator.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: translator-web
                port:
                  number: 80
