apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: page-translator-prod
#    envs:
#      - prod.env
#generatorOptions:
#  disableNameSuffixHash: true
#patches:
#  - target:
#      kind: Deployment
#      name: translator-web
#    patch: |-
#      - op: add
#        path: /spec/template/spec/containers/0/envFrom
#        value:
#          - configMapRef:
#              name: page-translator-prod
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
