apiVersion: v1
kind: Service
metadata:
  name: translator-web
  namespace: page-translator
  labels:
    app: translator-web
    app.kubernetes.io/name: translator-web
spec:
  type: LoadBalancer
  selector:
    app: translator-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      name: http

