apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-service
spec:
  selector:
    matchLabels:
      app: export-service
  replicas: 1
  template:
    metadata:
      labels:
        app: export-service
    spec:
      containers:
        - name: export-service
          image: "localhost:5001/page-translator/export-service:latest"
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-web
                  key: POSTGRES_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
