apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-service
spec:
  selector:
    matchLabels:
      app: export-service
  replicas: 1
  template:
    metadata:
      labels:
        app: export-service
    spec:
      containers:
        - name: export-service
          image: "a:5001/bambrikii/export-service:latest"
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: db-url
                  name: db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-username
                  name: db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: db
