apiVersion: v1
kind: Pod
metadata:
  name: postgresql-client
  labels:
    app: postgresql-client
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: postgresql-client
      image: andreswebs/postgresql-client
      imagePullPolicy: Always
      stdin: true
      tty: true
      command: ["/bin/sh"]
