apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: page_translator
  POSTGRES_USER: page_translator
  POSTGRES_PASSWORD: page_translator
